ODS/ODS/urls.py
from .                                    import views
from django.conf                          import settings
from django.conf.urls.static              import static
from django.contrib                       import admin
from django.contrib.auth                  import views as auth_views
from django.contrib.auth.views            import logout_then_login
from django.urls                          import path, include
# from Usuarios.views import (
#     PostListView, 
#     PostDetailView, 
#     PostCreateView, 
#     PostUpdateView, 
#     PostDeleteView
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.inicio, name="inicio"),
    path('users/', include('Usuarios.urls', namespace='usuarios')),
    path('accounts/', include('allauth.urls')),
    path('', views.Inicio.as_view(), name="inicio"),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
	path('logout/', auth_views.logout_then_login, name = "logout"),
    path('foro/', views.ForoUsuario.as_view(), name="foro" ),
    path('foroadmin/', views.ForoAdmin.as_view(), name="foroadmin")
    # path('', PostListView.as_view(), name='list'),
    # path('<slug>/', PostDetailView.as_view(), name='detail'),
    # path('<slug>/update', PostUpdateView.as_view(), name='update'),
    # path('<slug>/delete', PostDeleteView.as_view(), name='delete'),
    # path('create/', PostCreateView.as_view(), name='create')
    
]


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ODS/Usuarios/urls.py
from django.urls import path
from Usuarios.views import (
     Registrarme,
     PostListView, 
     PostDetailView, 
     PostCreateView, 
     PostUpdateView, 
     PostDeleteView
)


app_name = "usuarios"

urlpatterns = [
     path('Registrarme/', Registrarme.as_view(), name='registrarme'),
     path('create', PostCreateView.as_view(), name='create'),
     path('list', PostListView.as_view(), name='list'),
     path('post/<int:pk>/', PostDetailView.as_view(), name='detail'),
     path('post/<int:pk>/update', PostUpdateView.as_view(), name='update'),
     path('post/<int:pk>/delete', PostDeleteView.as_view(), name='delete'),
     


]

ODS/templates/posts/post_confirm_delete.html
{% extends "base.html"%}
{% load static %}

{% block content %}
    <div class="container">
        <h1>ELIMINAR POST</h1>
        <form  method="POST">
            {% csrf_token %}
            <h2>Seguro que desea eliminar el post {{ object.post_titulo }} ?</h2>
        
            <button class="btn btn-danger" type='submit'>Si, Eliminar</button>
            <a class="btn btn-secondary" href="{% url 'usuarios:detail' object.id_post %}">Cancelar</a>
        </form>
              
    </div>
{% endblock content %}
    

ODS/templates/posts/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block css %}
  {{ block.super }}  
    <!-- <link href="{% static 'css/post.css' %}" type="text/css" rel="stylesheet"> -->
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card" >
                <div class="card-body">
                    <div class="date-name">
                        <h4 class="card-title">{{object.titulo_post}}</h4>
                        <h5>Publicado por @{{object.author}}</h5>
                        <h5>{{object.fecha_hora}}</</h5>
                    </div>
                    
                    <h6>Categoria: {{ object.categoria_verbose }}{% if not forloop.last %}{% endif %} </h6>
                    <p class="card-text">{{object.contenido}}</p>

                    {% if object.author == user %}
                        <a href="{% url 'usuarios:update' object.id_post %}" class="btn btn-secondary">EDITAR</a>
                        <a href="{% url 'usuarios:delete' object.id_post %}" class="btn btn-danger">ELIMINAR</a>
                    {% endif %}
                </div>
            </div>
    </div>
{% endblock content %}
    

ODS/templates/posts/post_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
{{ block.super }}  
	<!-- <link href="{% static 'css/post.css' %}" type="text/css" rel="stylesheet"> -->
{% endblock %}

{% block content %}
	<div class="container">
		<h1>CREAR NUEVO POST</h1>
		<form action="{% url 'usuarios:create' %}" method="POST">
			{% csrf_token %}

			{{ form | crispy }}
		
			<button class="btn btn-primary" type='submit'>ENVIAR</button>
		</form>
			  
	</div>
{% endblock content %}

ODS/templates/posts/post_list.html
{% extends "base.html" %}
{% load static %}
{% block css %}
  {{ block.super }}  
	<!-- <link href="{% static 'css/post.css' %}" type="text/css" rel="stylesheet">  -->
{% endblock %}
{% block content %}
	<div class="container">
		{% for object in object_list %}
			<hr>
			<div class="card" style="width: 25rem;">
				<div class="card-body">
					<h4 class="card-title">{{object.titulo_post}}</h4>
					<h6>----- {{ object.categoria_verbose }}{% if not forloop.last %},{% endif %} -----</h6>
					<h5>Autor: {{object.author}} - {{object.fecha_hora}} </h5>
					<p class="card-text">{{object.contenido}}</p>
					<a href="{% url 'usuarios:detail' object.id_post %} " class="btn btn-primary">VER POST</a>
				</div>
			</div>
			<hr>	
		{% endfor %}
	</div>
{% endblock %}
	

ODS/templates/posts/post_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
{{ block.super }}  
	<!-- <link href="{% static 'css/post.css' %}" type="text/css" rel="stylesheet"> -->
{% endblock %}

{% block content %}
	<div class="container">
		<h1>EDITAR POST</h1>
		<form action="{% url 'usuarios:update' object.id_post %}" method="POST">
			{% csrf_token %}

			{{ form | crispy }}
		
			<button class="btn btn-primary" type='submit'>ENVIAR</button>
		</form>
			  
	</div>
{% endblock content %}