ODS/Foro/urls.py
from django.urls import path
from .views import *

app_name = "Foro"

urlpatterns = [
     path('foroadmin', ListarAdmin.as_view(), name='listaradmin'),

]

ODS/ODS/urls.py
from .                                    import views
from django.conf                          import settings
from django.conf.urls.static              import static
from django.contrib                       import admin
from django.contrib.auth                  import views as auth_views
from django.contrib.auth.views            import logout_then_login
from django.urls                          import path, include
# from Usuarios.views import (
#     PostListView, 
#     PostDetailView, 
#     PostCreateView, 
#     PostUpdateView, 
#     PostDeleteView
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.inicio, name="inicio"),
    path('users/', include('Usuarios.urls', namespace='usuarios')),
    path('accounts/', include('allauth.urls')),
    path('', views.Inicio.as_view(), name="inicio"),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
	path('logout/', auth_views.logout_then_login, name = "logout"),
    path('foro/', views.ForoUsuario.as_view(), name="foro" ),
    path('foroadmin/', views.ForoAdmin.as_view(), name="foroadmin")
    # path('', PostListView.as_view(), name='list'),
    # path('<slug>/', PostDetailView.as_view(), name='detail'),
    # path('<slug>/update', PostUpdateView.as_view(), name='update'),
    # path('<slug>/delete', PostDeleteView.as_view(), name='delete'),
    # path('create/', PostCreateView.as_view(), name='create')
    
]


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ODS/Usuarios/urls.py
from django.urls import path
from Usuarios.views import (
     Registrarme,
     PostListView, 
     PostDetailView, 
     PostCreateView, 
     PostUpdateView, 
     PostDeleteView
)


app_name = "usuarios"

urlpatterns = [
     path('Registrarme/', Registrarme.as_view(), name='registrarme'),
     path('create', PostCreateView.as_view(), name='create'),
     path('list', PostListView.as_view(), name='list'),
     path('post/<int:pk>/', PostDetailView.as_view(), name='detail'),
     path('post/<int:pk>/update', PostUpdateView.as_view(), name='update'),
     path('post/<int:pk>/delete', PostDeleteView.as_view(), name='delete'),
     


]

ODS/Foro/models.py
from django.db import models

# Create your models here.

ODS/Foro/forms.py
from .models            import Post
from django             import forms




class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = [
			'titulo_post',
			'contenido',
			'categoria',]
		labels = {
			'titulo_post': 'Titulo',
			'contenido': 'Contenido',
			'categoria': 'Categoria',
		}
		widgets = {
			'titulo_post': forms.TextInput(attrs={'class':'form_control'}),
			'contenido': forms.Textarea(attrs={'class':'form_control', 'rows':5, 'placeholder':'Ingrese contenido del  post.'}),
			'categoria': forms.Select(),
		}

ODS/Foro/views.py
from django.shortcuts         import render
from django.views.generic     import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from .forms import PostForm

class ListarAdmin(ListView):
    template_name = "templates/foroadmin.html"
    model = Post
    form_class = PostForm

    def get_queryset(self):
        return Post.objects.all()

class CrearAdmin(CreateView):
    template_name = "templates/crearpostadmin.html"
    model = Post
    form_class = PostForm

ODS/templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link href="{% static 'css/inicio.css' %}" type="text/css" rel="stylesheet">
    <title>ODS BLOG</title>
    {% block css %} {% endblock css %}

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


</head>

<body>
    {% include 'header.html' %}
    

    {% block contenido %}

    {% endblock contenido %}

    <footer class="container">
        {% comment %} <p>© INFORMATORIO 2021</p> {% endcomment %}
    </footer>
    </div>
    <script src="{% static 'js/inicio.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

</body>

</html>

ODS/templates/foro.html
{% extends "base.html" %}
{% load static %}
{% block header %}

{% endblock header %}
{% block contenido %}
<form class="form-label" method="POST"> {% csrf_token %}
    {% include "includes/form_errors.html" %}
    {{form.as_p}}
    <div class="row">
        <div class="col">
            <a href="{% url 'inicio' %}" class="btn btn-danger" style="padding:5px;">Cancelar</button>
            <button type="submit" class="btn btn-primary" style="padding:5px;">Guardar</button>
        </div>
    </div>
</form>



{% endblock contenido %}

ODS/templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'inicio' %}">17 ODS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Cerrar Sesion<span
                            class="sr-only">(current)</span></a>
                </li>
                
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Iniciar Sesion<span
                            class="sr-only">(current)</span></a>
                </li>
                {% endif %}
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'foroadmin' %}">Foro Admin</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'foro' %}">Foro</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

ODS/templates/inicio.html
{% extends "base.html" %}
{% load static %}

{% block contenido %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="2" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="3" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="4" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="5" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="6" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="7" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="8" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="9" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="10" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="11" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="12" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="13" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="14" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="15" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="16" class="active"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://i.imgur.com/MZtwZAe.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>1: Fin de la pobreza</h1>
          <p>Poner fin a la pobreza en todas sus formas en todo el mundo</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/poverty/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/jRFVU4I.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>2: Hambre Cero</h1>
          <p>Poner fin al hambre</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/hunger/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/ofpiako.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>3: Salud y Bienestar</h1>
          <p>Garantizar una vida sana y promover el bienestar para todos en todas las edades</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/health/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/gzJE53E.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>4: Educacion de Calidad</h1>
          <p>Poner fin al hambre</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/education/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/MXgI74y.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>5: Igualad de Genero</h1>
          <p>Lograr la igualdad entre los géneros y empoderar a todas las mujeres y las niñas</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/gender-equality/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/aDx0Leg.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>6: Agua limpia y Saneamiento</h1>
          <p>Garantizar la disponibilidad de agua y su gestión sostenible y el saneamiento para todos</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/water-and-sanitation/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/ubh7RcL.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>7: Energia Asequible y No Contaminante</h1>
          <p>Garantizar el acceso a una energía asequible, segura, sostenible y moderna</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/energy/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/ndhUtxK.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>8: Trabajo Decente y Crecimiento Economico</h1>
          <p>Promover el crecimiento económico inclusivo y sostenible, el empleo y el trabajo decente para todos</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/economic-growth/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/3Ia0sXS.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>9: Industria, Innovacion e Infrainstructura</h1>
          <p>Construir infraestructuras resilientes, promover la industrialización sostenible y fomentar la innovación
          </p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/infrastructure/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/hkZM0MI.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>10: Reducción de las Desigualdades</h1>
          <p>Reducir la desigualdad en y entre los países</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/inequality/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/l1YGUwG.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>11: Ciudades y Comunidades Sostenibles</h1>
          <p>Lograr que las ciudades sean más inclusivas, seguras, resilientes y sostenibles</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/cities/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/pxML9hz.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>12: Producción y Consumo Responsable</h1>
          <p>Garantizar modalidades de consumo y producción sostenibles</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/sustainable-consumption-production/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/010g4fu.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>13: Acción por el Clima</h1>
          <p>Adoptar medidas urgentes para combatir el cambio climático y sus efectos</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/climate-change-2/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/5nVFSxt.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>14: Vida Submarina</h1>
          <p>Conservar y utilizar sosteniblemente los océanos, los mares y los recursos marinos</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/oceans/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/WONBRQa.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>15: Vida de Ecosistemas terrestres</h1>
          <p>Gestionar sosteniblemente los bosques, luchar contra la desertificación, detener e invertir la degradación
            de las tierras, detener la pérdida de biodiversidad</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/biodiversity/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/0ZoKp8G.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>16: Paz, Justicia e Instituciones Solidas</h1>
          <p>Promover sociedades justas, pacíficas e inclusivas</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/peace-justice/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/3ARK7H5.png">
      <div class="container">
        <div class="carousel-caption">
          <h1>17: Alianzas para Lograr Objetivos</h1>
          <p>Revitalizar la Alianza Mundial para el Desarrollo Sostenible</p>
          <p><a class="btn btn-lg btn-primary" href="https://www.un.org/sustainabledevelopment/es/globalpartnerships/" Target="_blank" role="button">Leer más</a></p>
        </div>
      </div>
    </div>
  </div>


  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container marketing">

  <hr class="featurette-divider">

  
    </main>
    <script src="{% static 'js/inicio.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
{% endblock contenido %}

ODS/templates/login.html
{% load static %}
{% load crispy_forms_tags %}

<!--
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
	<meta name="generator" content="Hugo 0.88.1">
	<title>Login</title>

	<link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

	<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
	<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
	<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
	<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
	<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
	<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
	<meta name="theme-color" content="#7952b3">


	<style>
	.bd-placeholder-img {
		font-size: 1.125rem;
		text-anchor: middle;
		-webkit-user-select: none;
		-moz-user-select: none;
		user-select: none;
	}

	@media (min-width: 768px) {
		.bd-placeholder-img-lg {
		font-size: 3.5rem;
		}
	}
	</style>       
	
  </head>
<body class="text-center">

-->
{% block css %}
<link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
	integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">
<link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container-form">
	<main class="form-signin">

		<h1>INICIAR SESION</h1>
		<form method="POST">
			{% csrf_token %}
			<!--<img class="mb-4" src="/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">-->
			{% include "includes/form_errors.html" %}
			<div class="form-floating">
				<input type="text" class="form-control" id="InputUsername" placeholder="Nombre de Usuario"
					name="username">
				<label for="InputUsername">Nombre de Usuario</label>
			</div>
			<div class="form-floating">
				<input type="password" class="form-control" id="InputPassword" placeholder="Contraseña" name="password">
				<label for="InputPassword">Contraseña</label>
			</div>

			<div class="checkbox mb-3">
				<label><input type="checkbox" value="remember-me"> Recordarme</label>
			</div>
			<button class="w-100 btn btn-lg btn-primary" type="submit">Iniciar sesion</button>
			<p class="mt-5 mb-3 text-muted"><a href="{% url 'inicio' %}">Volver al inicio</a></p>
			<p class="mt-5 mb-3 text-muted"><a href="{% url 'usuarios:registrarme' %}">Registrarme</a></p>
		</form>
	</main>
</div>

{% endblock %}